package com.example.groceryapp

import android.content.Intent
import android.os.Build
import android.os.Bundle
import android.util.Log
import android.view.View
import android.widget.*
import androidx.annotation.RequiresApi
import androidx.appcompat.app.AlertDialog
import androidx.appcompat.app.AppCompatActivity
import com.android.volley.Request
import com.android.volley.Response
import com.android.volley.toolbox.StringRequest
import com.example.groceryapp.Adapter.MySingleton
import org.json.JSONObject
import java.time.LocalDateTime
import java.time.format.DateTimeFormatter
import java.time.format.FormatStyle


class Checkout : AppCompatActivity() {

    lateinit var paymentMethod:String
    lateinit var deliveryMethod:String
    lateinit var address:EditText
    lateinit var notes:EditText
    lateinit var amount:String


    @RequiresApi(Build.VERSION_CODES.O)
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_checkout)

        val backButton: ImageButton = findViewById(R.id.back3)
        backButton.setOnClickListener {
            finish()
        }

        //radio group credit: https://www.geeksforgeeks.org/radiobutton-in-kotlin/
        //Delivery Radio Group
        val payment_radio_group:RadioGroup = findViewById(R.id.payment)
        payment_radio_group.setOnCheckedChangeListener(
            RadioGroup.OnCheckedChangeListener { group, checkedId ->
                val radio: RadioButton = findViewById(checkedId)
                Toast.makeText(applicationContext,"Payment Choice :"+
                        " ${radio.text}",
                    Toast.LENGTH_SHORT).show()
                paymentMethod= "${radio.text}"
            })

        //Delivery Radio Group
        val delivery_radio_group:RadioGroup = findViewById(R.id.delivery)
        delivery_radio_group.setOnCheckedChangeListener(
            RadioGroup.OnCheckedChangeListener { group, checkedId ->
                val radio: RadioButton = findViewById(checkedId)
                Toast.makeText(applicationContext,"Delivery Choice :"+
                        " ${radio.text}",
                    Toast.LENGTH_SHORT).show()
                 deliveryMethod= "${radio.text}"
            })

        //Payment Amount Text
        var payment_amount:TextView = findViewById(R.id.amount)
        amount = intent.getStringExtra("amount").toString()
        payment_amount.text = "RM " + amount

        address = findViewById(R.id.address)
        notes= findViewById(R.id.note)

        //When user click on pay button
        val pay:Button = findViewById(R.id.pay)
        pay.setOnClickListener {

            //need to ensure radio button is checked (for payment field and delivery field)
            //delivery address cannot be empty
            if(address.text.isEmpty()){
                address.error = "Delivery Address is required!";
                address.requestFocus();
            }
            else{
                //FLOW:DATABASE PHP
                //Step0: get the order_id
                //Step1: get the user's cart_id
                //Step2: get all the product's in the cart_id
                //Step3: insert all the items in cartitems to the orderitems table
                //Step4: delete all the items in the cartitems

                //FLOW:ANDROID STUDIO
                //order_id, payment_id, delivery_id with relative info need to be write to database
                //order_id is generated by the server, but payment_id and delivery_id is generate by here
                //the cart items have to be clear :)
                //move the cart items to the orderitems table (do at backend)
                //get the current date and time to write to database
                //writeOrder()

                //after user successfully place order, we will display a dialog showing that order have placed successfully.
                openDialog()
            }
        }
    }

    private fun openDialog() {
        // create an alert builder
        val builder = AlertDialog.Builder(this)
        builder.setTitle("Thank You for CHOOSING US")

        // set the custom layout
//        val customLayout: View = layoutInflater.inflate(R.layout.mydialog, null);
//        builder.setView(customLayout);

        builder.setMessage("You have place an order successfully! Kindly wait for seller to ship your item(s). Have a nice day :)")
        builder
                .setPositiveButton(
                        "OK"
                ) { dialog, _ -> // When the user click ok button
                    //close the dialog
                    dialog.cancel()
                    //bring the user back to menu
                    startActivity(Intent(this, MainActivity::class.java))
                }


        // create and show the alert dialog
        val dialog: AlertDialog = builder.create()
        dialog.show()

    }

    //able to write order but can't response to user so far
    @RequiresApi(Build.VERSION_CODES.O)
    private fun writeOrder() {

        //record the date and time when user place order to add to database
        //credit to:https://grokonez.com/kotlin/kotlin-get-current-datetime#I_Kotlin_8211_Get_Current_DateTime
        val currentDateTime = LocalDateTime.now()
        var date:String = currentDateTime.format(DateTimeFormatter.ISO_DATE)
        var time:String = currentDateTime.format(DateTimeFormatter.ofPattern("HH:mm:ss"))

        //variable to write to server
        var order = (Math.random()*100000000).toInt()
        val order_number:String = String.format("%08d",order)

        var delivery = (Math.random()*100000000).toInt()
        val delivery_id:String = "D" + String.format("%08d",delivery)

        var payment = (Math.random()*100000000).toInt()
        val payment_id:String = "P" + String.format("%08d",payment)

        var user_id = 1

        //write order details to database using json
        val info:String = "https://groceryapptarucproject.000webhostapp.com/grocery/order/insertorder.php"+
                "?order_number=$order_number&payment_amount=$amount" + "&payment_method=$paymentMethod&delivery_address=${address.text}&user_id=$user_id&delivery_id=$delivery_id&payment_id=$payment_id&delivery_method=$deliveryMethod&order_date=$date&order_time=$time"
        Log.e("winnie",info)

        val stringRequest = StringRequest(Request.Method.GET, info,
                Response.Listener<String> { response ->
                    Log.e("winnie", response)

                    try{
                        if(response != null){
                            val strResponse = response.toString()
                            val jsonResponse  = JSONObject(strResponse)
                            val success: String = jsonResponse.get("success").toString()

                            if(success == "1"){
                                Toast.makeText(this,"Loading... ", Toast.LENGTH_LONG).show()

                            }else{
                                Toast.makeText(this, "Error occured. Please try again later", Toast.LENGTH_LONG).show()
                            }

                        }
                    }catch (e:Exception){
                        Log.d("Main", "Response: %s".format(e.message.toString()))
                    }

                },
                Response.ErrorListener { error -> Log.d("Main", "Response: %s".format(error.message.toString())) })

        // Add the request to the RequestQueue.
        MySingleton.getInstance(this).addToRequestQueue(stringRequest)


        //update orderitems, remove cartitems
        val url:String =  "https://groceryapptarucproject.000webhostapp.com/grocery/order/insertcartitemsintoorderitems.php" +
                "?order_number=" + order_number  + "&user_id=" + user_id
        Log.e("winnie",url)

        val stringRequest1 = StringRequest(Request.Method.GET, url,
                Response.Listener<String> { response ->
                    Log.e("winnie", response)

                    try{
                        if(response != null){
                            val strResponse = response.toString()
                            val jsonResponse  = JSONObject(strResponse)
                            val success: String = jsonResponse.get("success").toString()

                            if(success == "1"){
                                Toast.makeText(this,"Order placed successfully.", Toast.LENGTH_LONG).show()

                            }else{
                                Toast.makeText(this, "Error occured. Please try again later", Toast.LENGTH_LONG).show()
                            }

                        }
                    }catch (e:Exception){
                        Log.d("Main", "Response: %s".format(e.message.toString()))
                    }

                },
                Response.ErrorListener { error -> Log.d("Main", "Response: %s".format(error.message.toString())) })

        // Add the request to the RequestQueue.
        MySingleton.getInstance(this).addToRequestQueue(stringRequest1)

    }
}