package com.example.groceryapp

import android.os.Bundle
import android.util.Log
import android.widget.*
import androidx.appcompat.app.AppCompatActivity

class Checkout : AppCompatActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_checkout)

        val backButton: ImageButton = findViewById(R.id.back3)
        backButton.setOnClickListener {
            finish()
        }

        //radio group credit: https://www.geeksforgeeks.org/radiobutton-in-kotlin/
        //Delivery Radio Group
        val payment_radio_group:RadioGroup = findViewById(R.id.payment)
        payment_radio_group.setOnCheckedChangeListener(
            RadioGroup.OnCheckedChangeListener { group, checkedId ->
                val radio: RadioButton = findViewById(checkedId)
                Toast.makeText(applicationContext,"Payment Choice :"+
                        " ${radio.text}",
                    Toast.LENGTH_SHORT).show()
            })

        //Delivery Radio Group
        val delivery_radio_group:RadioGroup = findViewById(R.id.delivery)
        delivery_radio_group.setOnCheckedChangeListener(
            RadioGroup.OnCheckedChangeListener { group, checkedId ->
                val radio: RadioButton = findViewById(checkedId)
                Toast.makeText(applicationContext,"Delivery Choice :"+
                        " ${radio.text}",
                    Toast.LENGTH_SHORT).show()
            })

        //Payment Amount Text
        var payment_amount:TextView = findViewById(R.id.amount)
        val amount:String? = intent.getStringExtra("amount")
        payment_amount.text = "RM " + amount

        val address:EditText = findViewById(R.id.address)
        val notes:EditText = findViewById(R.id.note)

        //When user click on pay button
        val pay:Button = findViewById(R.id.pay)
        pay.setOnClickListener {
            //HERE ARE SOME TO DO
            //order_id, payment_id, delivery_id with relative info need to be write to database
            //order_id is generated by the server, but payment_id and delivery_id is gengerate by here
            //the cart items have to be clear :)

            writeOrder()

        }

    }

    private fun writeOrder() {
        Log.e("winnie","write order to database")
    }
}